### ISSUE TITLE
ImportError: No module named 'pip'

### ISSUE THREAD

**Issue by adsahay** [kennethreitz/conda-buildpack#19]
Here's my `conda-requirements.txt`

```
pip=8.0.1=py34_0
setuptools=19.4=py34_0
conda=3.19.0=py34_0
conda-env=2.4.5=py34_0
requests=2.9.1=py34_0
numpy=1.9.2=py34_0
python=3.5.1=0
scipy=0.16.0=np19py34_0
```

I get this error while building:

```
-----> Installing dependencies using Pip
Traceback (most recent call last):
  File "/app/.heroku/miniconda/bin/pip", line 4, in <module>
    import pip
ImportError: No module named 'pip'
 !     Push rejected, failed to compile Python/Conda app
1.9.2-py  51% |###############                | Time: 0:00:00  27.04 MB/s
       requests-2.9.1   0% |                              | ETA:  --:--:--   0.00  B/s
       setuptools-19.   0% |                              | ETA:  --:--:--   0.00  B/s
       conda-3.19.0-p   0% |                              | ETA:  --:--:--   0.00  B/s
       pip-8.0.1-py34   0% |                              | ETA:  --:--:--   0.00  B/s
########################      | Time: 0:00:00  28.97 MB/s
       scipy-0.16.0-n   0% |                              | ETA:  --:--:--   0.00  B/s
00:00  38.30 MB/s
                      | Time: 0:00:00  39.53 MB/s
s
      | Time: 0:00:00  40.06 MB/s
  81% |#########################      | Time: 0:00:00  40.47 MB/s
00:00  40.79 MB/s
       Extracting packages ...
       [                    ]|                                                  |   0%
       Unlinking packages ...
       [      COMPLETE      ]|                                                  |   0%
       Linking packages ...
       [      COMPLETE      ]|                                                  |   0%
-----> Installing dependencies using Pip
Traceback (most recent call last):
  File "/app/.heroku/miniconda/bin/pip", line 4, in <module>
    import pip
ImportError: No module named 'pip'
 !     Push rejected, failed to compile Python/Conda app
########################      | Time: 0:00:00  28.97 MB/s
       scipy-0.16.0-n   0% |                              | ETA:  --:--:--   0.00  B/s
00:00  38.30 MB/s
                      | Time: 0:00:00  39.53 MB/s
s
      | Time: 0:00:00  40.06 MB/s
  81% |#########################      | Time: 0:00:00  40.47 MB/s
00:00  40.79 MB/s
       Extracting packages ...
       [                    ]|                                                  |   0%
       Unlinking packages ...
       [      COMPLETE      ]|                                                  |   0%
       Linking packages ...
       [      COMPLETE      ]|                                                  |   0%
-----> Installing dependencies using Pip
Traceback (most recent call last):
  File "/app/.heroku/miniconda/bin/pip", line 4, in <module>
    import pip
ImportError: No module named 'pip'
 !     Push rejected, failed to compile Python/Conda app
00:00  38.30 MB/s
                      | Time: 0:00:00  39.53 MB/s
s
      | Time: 0:00:00  40.06 MB/s
  81% |#########################      | Time: 0:00:00  40.47 MB/s
00:00  40.79 MB/s
       Extracting packages ...
       [                    ]|                                                  |   0%
       Unlinking packages ...
       [      COMPLETE      ]|                                                  |   0%
       Linking packages ...
       [      COMPLETE      ]|                                                  |   0%
-----> Installing dependencies using Pip
Traceback (most recent call last):
  File "/app/.heroku/miniconda/bin/pip", line 4, in <module>
    import pip
ImportError: No module named 'pip'
 !     Push rejected, failed to compile Python/Conda app
                      | Time: 0:00:00  39.53 MB/s
s
      | Time: 0:00:00  40.06 MB/s
  81% |#########################      | Time: 0:00:00  40.47 MB/s
00:00  40.79 MB/s
       Extracting packages ...
       [                    ]|                                                  |   0%
       Unlinking packages ...
       [      COMPLETE      ]|                                                  |   0%
       Linking packages ...
       [      COMPLETE      ]|                                                  |   0%
-----> Installing dependencies using Pip
Traceback (most recent call last):
  File "/app/.heroku/miniconda/bin/pip", line 4, in <module>
    import pip
ImportError: No module named 'pip'
 !     Push rejected, failed to compile Python/Conda app
s
      | Time: 0:00:00  40.06 MB/s
  81% |#########################      | Time: 0:00:00  40.47 MB/s
00:00  40.79 MB/s
       Extracting packages ...
       [                    ]|                                                  |   0%
       Unlinking packages ...
       [      COMPLETE      ]|                                                  |   0%
       Linking packages ...
       [      COMPLETE      ]|                                                  |   0%
-----> Installing dependencies using Pip
Traceback (most recent call last):
  File "/app/.heroku/miniconda/bin/pip", line 4, in <module>
    import pip
ImportError: No module named 'pip'
 !     Push rejected, failed to compile Python/Conda app
      | Time: 0:00:00  40.06 MB/s
  81% |#########################      | Time: 0:00:00  40.47 MB/s
00:00  40.79 MB/s
       Extracting packages ...
       [                    ]|                                                  |   0%
       Unlinking packages ...
       [      COMPLETE      ]|                                                  |   0%
       Linking packages ...
       [      COMPLETE      ]|                                                  |   0%
-----> Installing dependencies using Pip
Traceback (most recent call last):
  File "/app/.heroku/miniconda/bin/pip", line 4, in <module>
    import pip
ImportError: No module named 'pip'
 !     Push rejected, failed to compile Python/Conda app
  81% |#########################      | Time: 0:00:00  40.47 MB/s
00:00  40.79 MB/s
       Extracting packages ...
       [                    ]|                                                  |   0%
       Unlinking packages ...
       [      COMPLETE      ]|                                                  |   0%
       Linking packages ...
       [      COMPLETE      ]|                                                  |   0%
-----> Installing dependencies using Pip
Traceback (most recent call last):
  File "/app/.heroku/miniconda/bin/pip", line 4, in <module>
    import pip
ImportError: No module named 'pip'
 !     Push rejected, failed to compile Python/Conda app
00:00  40.79 MB/s
       Extracting packages ...
       [                    ]|                                                  |   0%
       Unlinking packages ...
       [      COMPLETE      ]|                                                  |   0%
       Linking packages ...
       [      COMPLETE      ]|                                                  |   0%
-----> Installing dependencies using Pip
Traceback (most recent call last):
  File "/app/.heroku/miniconda/bin/pip", line 4, in <module>
    import pip
ImportError: No module named 'pip'
 !     Push rejected, failed to compile Python/Conda app
```

How do I get around this?

**Comment by kennethreitz** [comment]
This may be caused by you providing `pip` in your `conda-requirements.txt` file. It is not necessary.
